name: joya
description: A new Flutter project.
publish_to: "none" # Remove this line if you wish to publish to pub.dev
version: 0.0.0

environment:
  sdk: ">=2.15.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  mockito: ^5.0.17
  bloc_test: ^9.0.2
  curved_navigation_bar: ^1.0.1
  dio: ^4.0.6
  qr_code_scanner: ^0.7.0
  json_annotation: ^4.4.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  json_serializable: ^6.0.0
  build_runner: ^2.0.0

flutter:
  assets:
    #    - assets/images/joyalogo.png
    #    - assets/images/emailcheck.png
    - assets/images/error_window.png
    - assets/images/joyalogo.png
    - assets/images/qrcode.png
  uses-material-design: true
  fonts:
    - family: DMSans-Bold
      fonts:
        - asset: assets/fonts/DMSans-Bold.ttf
        - asset: assets/fonts/DMSans-Regular.ttf
