class MainTextPalettes {
  static const Map<String, String> textFr = {
    "EMAIL_LABEL_DEFAULT_TEXTFIELD": "Adresse e-mail",
    "PASSWORD_LABEL_DEFAULT_TEXTFIELD": "Mot de passe",
    "NAME_LABEL_DEFAULT_TEXTFIELD": "Nom",
    "SURNAME_LABEL_DEFAULT_TEXTFIELD": "Prénom",
    "CONFIRMATION_PASSWORD_LABEL_DEFAULT_TEXTFIELD": "Confirmation du mot de passe",
    "CONNEXION_BUTTON_DEFAULT_TEXTFIELD": "Connexion",
    "CONFIRMATIONMAIL_BUTTON_DEFAULT_TEXTFIELD": "Ouvrir Mail",
    "RECUPERTION_COMPTE_BUTTON_DEFAULT_TEXTFIELD": "Récupérer mon compte",
    "INSCRIPTION": "Inscription",
    "BIENVENUE": "BIENVENUE",
    "VOS_PLANTES": "Vos plantes connectées 🌱",
    "PLUSINFO":"Plus d’informations",
    "CONDITIONURL":"Condition d’utilisation & confidentialité.",
    "RECUP":"Mot de passe oublié ?",
    "REGARDEBOITE":"Regarde ta boite mail !",
    "TEXTSENDEMAIL":"Pour confirmer ton adresse mail, ouvre le mail que tu as reçu et clique sur le lien !",
    "TEXT CONFIRM MAIL QUESTION":"Tu as un compte ?",
    "QUESTION EMAIL":"Connecte toi",
    "OPENMAIL":"Ouvrir Mail",
    "ABOUT":"Paramètres",
    "ABOUTPRENIUM":"Devenir membre premium",
    "ABOUTNOTIF":"Notifications",
    "ABOUTDECO":"Déconnexion",
    "NOPLANT":"Aucune plante ajoutée.",
    "ADDFIRSTPLANT":"Ajoutez votre première plante en appuyant sur le bouton de scanner.",
    "SUIVANT":"Suivant",
    "VALIDER":"Valider",
    "CONFIG_PLANT":"Configurer ma plante",
    "NAME_PLANT":"Nom de ma plante",
    "LOCALISATION_PLANT":"Localisation de ma plante",
    "CONNECT_PLANT":"Connecter ma plante",
    "SCAN_QRCODE":"Scannez le QR code de votre capteur pour pouvoir établir la connexion.",
    "ABOUT_MY_ACCOUNT":"Mon compte",
    "ABOUT_HELP":"FAQ / Aide",
    "ABOUT_JOYA":"À propos de Joya",
    "MY_PLANT":"Mes plantes",
    "SEARCH":"Rechercher",
    "ERROR_EMAIL":"Adresse mail incorrect",
    "ABOUT_SETTING":"Parametre d'application",
    "VIDE":"",
    "BUILD":"Site en cours de construction",
    "DELETE_ACCOUNT":"Supprimer de mon compte",
    "ERROR_PASSWORD":"Mots de passe incorrect"

  };
}
